language: go
go:
  - 1.7
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

script:
  - docker build -f Dockerfile -t invocaops/flashpaper:$TAG .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push invocaops/flashpaper:$TAG;
